version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

executors:
  build:
    docker:
      - image: envoyproxy/envoy-build:cb15cc3d2010aff77d6e022ddf6d723fa8becbc0
    working_directory: ~/envoy

jobs:
  build:
    executor: build
    steps:
      - checkout
      - run: bazel build //source/exe:envoy
