version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

executors:
  build:
    docker:
      - image: envoyproxy/envoy-build:cb15cc3d2010aff77d6e022ddf6d723fa8becbc0
    working_directory: ~/envoy

jobs:
  build:
    executor: build
    steps:
      - checkout
      - run: |
          bazel build \
            --host_jvm_args=-Xmx1g \
            --discard_analysis_cache  \
            --notrack_incremental_state \
            --nokeep_state_after_build \
            //source/exe:envoy
